### ISSUE TITLE
Explain sd_text_to_video numframes and fps

### ISSUE THREAD

**Issue by SoftologyPro** [Artiprocher/DiffSynth-Studio#10]
numframes default is 64
fps default is 120

Shouldn't this make a video lasting approx half a second?  But it makes a 4 second video?

If I wanted a 10 second video at 30 fps, what would I set the numframes and fps to?

**Comment by Artiprocher** [comment]
`num_frames=300` and `fps=30`.

**Comment by SoftologyPro** [comment]
Using 300 and 30 gives the error
RuntimeError: The size of tensor a (64) must match the size of tensor b (300) at non-singleton dimension 0
