### ISSUE TITLE
关于推理速度

### ISSUE THREAD

**Issue by lichtud** [Artiprocher/DiffSynth-Studio#35]
请问下如果使用sdxl_lightling的话，是不是推理速度会有提升。我现在4090单卡渲染20秒的视频花了快两个小时才好。

**Comment by lichtud** [comment]
按照demo复现，对比看了下，动作基本是一致的，背景也没崩就是有点模糊，手偶尔有人影。
大佬真厉害
![1715152752506](https://github.com/Artiprocher/DiffSynth-Studio/assets/99418115/eee19b39-d9e5-42ba-9069-48b96a4539e2)
不过生成视频速度好慢，不知道大佬有没有优化方向？字节那个sdxl_lightling模型倒是 出图很快。

**Comment by Artiprocher** [comment]
sdxl 还没有特别完善的 controlnet，因此三渲二暂不支持 sdxl 架构的模型

**Comment by lichtud** [comment]
> sdxl 还没有特别完善的 controlnet，因此三渲二暂不支持 sdxl 架构的模型

好的，我看sdxl的 controlnet确实没有sd1.5的好。
