### ISSUE TITLE
mat1 and mat2 shapes cannot be multiplied

### ISSUE THREAD

**Issue by cnh-boom** [Artiprocher/DiffSynth-Studio#37]
![image](https://github.com/Artiprocher/DiffSynth-Studio/assets/68490560/6dd8c04a-c83f-419f-b90c-251c9e95b057)
When toon shading, two matrix shapes cannot be multiplied

**Comment by Artiprocher** [comment]
I think your input is not valid. For example, you enable some ControlNets but doesn't provide any frames as input. Please check it by yourself or post your parameters here.

**Comment by cnh-boom** [comment]
Thank you for your answer. The issue has been successfully resolved
