### ISSUE TITLE
Please help,why IndexError: 2400?

### ISSUE THREAD

**Issue by randompaga** [Artiprocher/DiffSynth-Studio#4]
input_video = [video[i] for i in range(40*60 41*60)]
  File "/code/./diffsynth/data/video.py", line 121, in __getitem__
    frame = self.data.__getitem__(item)
  File "/code/./diffsynth/data/video.py", line 15, in __getitem__
    return Image.fromarray(np.array(self.reader.get_data(item))).convert("RGB")
  File "/opt/conda/lib/python3.10/site-packages/imageio/core/format.py", line 437, in get_data
    raise IndexError(index)
IndexError: 2400

**Comment by gladzhang** [comment]
我也遇到了这个问题，Video类型提取帧时，遇到后面的帧无法通过__getitem__()调用，导致出现IndexError； 另外，我想问下视频转绘的长度需要是animatediff_stride的倍数吗，有一些长度的视频会报错

**Comment by Cococyh** [comment]
> ```
> input_video = [video[i] for i in range(40*60 41*60)]
> ```
> 
> File "/code/./diffsynth/data/video.py", line 121, in **getitem** frame = self.data.**getitem**(item) File "/code/./diffsynth/data/video.py", line 15, in **getitem** return Image.fromarray(np.array(self.reader.get_data(item))).convert("RGB") File "/opt/conda/lib/python3.10/site-packages/imageio/core/format.py", line 437, in get_data raise IndexError(index) IndexError: 2400

maybe your video do not have 40*60=2400 frames

**Comment by gladzhang** [comment]
还有一个办法，就是利用ffmpeg提前切割视频，然后传入VideoData对应的image folder

**Comment by Artiprocher** [comment]
In this example, we use the frames starting from the 40th frame and ending at 41th frame. If you want to use the first 60 frames, you need to modify the code.

```python
input_video = [video[i] for i in range(0, 60)]
```

**Comment by Artiprocher** [comment]
Sorry for the late reply, I was very busy recently.

**Comment by randompaga** [comment]
> Sorry for the late reply, I was very busy recently.

THANKS!!!

**Comment by randompaga** [comment]
> frames

Yeah,you're right.

**Comment by randompaga** [comment]
> 还有一个办法，就是利用ffmpeg提前切割视频，然后传入VideoData对应的image folder

Thanks for your help.
