### ISSUE TITLE
Repo is difficult to set up.  Would appreciate an easy, working Colab notebook

### ISSUE THREAD

**Issue by Tylersuard** [Artiprocher/DiffSynth-Studio#8]
Hello.  I tried installing this locally, it took around an hour, and it did not work.  I tried installing it on Colab, that took another hour, and it did not work.  It would be nice to have a notebook attached to this repo so we can just click "run all" and try it out.  Thank you for making this repo though.

**Comment by Artiprocher** [comment]
Thanks for your advice. This project is still in development and I am very busy ... So it may need more time.

**Comment by Artiprocher** [comment]
@Tylersuard Done! See [here](https://colab.research.google.com/github/Artiprocher/DiffSynth-Studio/blob/main/examples/Diffutoon_toon_shading.ipynb). An example of toon shading on Colab.

**Comment by Tylersuard** [comment]
@Artiprocher This is amazing, thank you!  Is the guide video the same file as the input video?

**Comment by Artiprocher** [comment]
@Tylersuard Maybe the filename is confusing. I updated the Colab example. Rename it as "input_video.mp4". Additionally, the video editing feature is also supported in this example. Have fun~

**Comment by goku-kakarot-7227** [comment]
> @Tylersuard Done! See [here](https://colab.research.google.com/github/Artiprocher/DiffSynth-Studio/blob/main/examples/Diffutoon.ipynb). An example of toon shading on Colab.

Is this notebook shifted to other link? Can you please share that. Thanks!
